a=int(input("enter the first number:"))
b=int(input("enter the second number:"))
print("addition:",a+b)
print("subtraction:",a-b)
print("multiplication:",a*b)
print("divition:",a/b)
print("floor diviton:",a//b)
print("exponentiation:",a**b)
print("modulus:",a%b)